name: niagarea
description: "Aplikasi pencatatan pulsa & token dengan integrasi Digiflazz"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Tema
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # Database (Drift - SQLite ORM type-safe)
  drift: ^2.25.0
  drift_flutter: ^0.2.0
  sqlite3_flutter_libs: ^0.5.28
  path_provider: ^2.1.5
  path: ^1.9.1

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # HTTP Client (untuk Digiflazz API)
  dio: ^5.8.0+1

  # Utilitas
  intl: ^0.20.2
  crypto: ^3.0.6
  flutter_secure_storage: ^9.2.4
  uuid: ^4.5.1

  # Grafik Statistik
  fl_chart: ^0.70.2
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  google_sign_in: 6.2.1
  url_launcher: ^6.3.2
  connectivity_plus: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqlite3: ^2.1.0
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4

  # Code Generation
  drift_dev: ^2.25.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
